CREATE TABLE Users (
	user_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
	user_name VARCHAR2(20) UNIQUE NOT NULL,
	user_gender VARCHAR2(20),
	user_age NUMBER,
	PRIMARY KEY(user_id)
);

INSERT INTO Users (user_name, user_gender, user_age)
VALUES ('testUser', 'Male', 42);
